version: '3.8'

services:
  db:
    image: postgres:17
    container_name: totsuko-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: totsuko
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql_init.sql:/docker-entrypoint-initdb.d/sql_init.sql 

volumes:
  pgdata: